services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    hostname: nginx_reverse_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl/live
    extra_hosts:
      - "backendserver:123.123.0.1"
    networks:
      - frontend
    restart: always

networks:
  frontend:
    external: true
